data_dir: "data/dataset"

# hyperparameters
epochs: 10
learning_rate: 0.01
batch_size: 128

# scale the data
scaled: false

# model
hidden_units: 32
num_heads: 4
num_layers: 3

# task 2
task_2:
  num_heads: [4,8,16]
  embed_mlp: false
  top_layer_mlp: false

# task 3
task_3:

# plot
seed: 42
num_plot_rows: 3
num_plot_cols: 3
save_dir: "plots/task1"