data_dir: "data/dataset"

# hyperparameters
epochs: 100
learning_rate: 0.3
batch_size: 128

# scale the data
scaled: false

# model
hidden_units: 32
num_heads: 4
num_layers: 2
output_dim: 2

# plot
seed: 42
num_plot_rows: 3
num_plot_cols: 3